---
# Playbook 36: Create MinIO Bucket and Upload Files
# This playbook ensures the MinIO Client is installed, creates a bucket, uploads files to the bucket,
# and verifies their presence using dynamic IPs from the inventory.

- name: Notify user about Playbook 36
  hosts: localhost
  tasks:
    - name: Display playbook message
      ansible.builtin.debug:
        msg: "Running Playbook 36: Create MinIO Bucket and Upload Files - This playbook ensures the MinIO Client is installed, creates a bucket, uploads files, and verifies their presence on the storage node."

- name: Create MinIO bucket and upload files
  hosts: management
  become: true
  vars:
    minio_host: "{{ hostvars[groups['storage'][0]].inventory_hostname }}"  # Dynamically fetch storage node IP

  tasks:
    # Step 1: Read MinIO password from file
    - name: Read MinIO password from file
      ansible.builtin.slurp:
        src: /home/almalinux/miniopass
      register: minio_password_file

    - name: Set MinIO environment variable
      ansible.builtin.set_fact:
        mc_env:
          MC_HOST_local: "https://myminioadmin:{{ minio_password_file.content | b64decode }}@{{ minio_host }}:9000"

    # Step 2: Ensure the MinIO Client (mc) is installed
    - name: Ensure the MinIO Client (mc) is installed
      shell: |
        /usr/local/bin/mc --version
      environment: "{{ mc_env }}"
      register: mc_version
      changed_when: false
      failed_when: mc_version.rc != 0

    # Step 3: Create MinIO bucket
    - name: Create MinIO bucket
      shell: "/usr/local/bin/mc --insecure mb local/summary"
      environment: "{{ mc_env }}"
      register: create_bucket
      changed_when: create_bucket.rc == 0
      failed_when: "'already own it' not in create_bucket.stderr and create_bucket.rc != 0"

    # Step 4: Copy plDDT_means.csv to MinIO bucket
    - name: Copy plDDT_means.csv to MinIO bucket
      shell: "/usr/local/bin/mc --insecure cp /mnt/minio/Merizo/Merizo/plDDT_means.csv local/summary/"
      environment: "{{ mc_env }}"
      register: copy_plddt
      failed_when: copy_plddt.rc != 0

    # Step 5: Copy human_cath_summary.csv to MinIO bucket
    - name: Copy human_cath_summary.csv to MinIO bucket
      shell: "/usr/local/bin/mc --insecure cp /mnt/minio/Merizo/Merizo/human_cath_summary.csv local/summary/"
      environment: "{{ mc_env }}"
      register: copy_human
      failed_when: copy_human.rc != 0

    # Step 6: Copy ecoli_cath_summary.csv to MinIO bucket
    - name: Copy ecoli_cath_summary.csv to MinIO bucket
      shell: "/usr/local/bin/mc --insecure cp /mnt/minio/Merizo/Merizo/ecoli_cath_summary.csv local/summary/"
      environment: "{{ mc_env }}"
      register: copy_ecoli
      failed_when: copy_ecoli.rc != 0

    # Step 7: Verify files in the MinIO bucket
    - name: Verify files in the MinIO bucket
      shell: "/usr/local/bin/mc --insecure ls local/summary/"
      environment: "{{ mc_env }}"
      register: verify_files

    # Step 8: Display verification output
    - name: Display verification output
      debug:
        msg: "{{ verify_files.stdout }}"
