---
- name: Run all required playbooks in sequence to get results
  hosts: localhost
  gather_facts: no
  tasks: []

- import_playbook: p33_run_spark_job_for_ecoli.yml
- import_playbook: p34_run_spark_job_for_human.yml
- import_playbook: p34_run_spark_job_for_human.yml
- import_playbook: p36_put_results_to_minio.yml
- import_playbook: p37_copy_csv_result_to_local.yml
