#cloud-config
bootcmd:
  - [ dnf, config-manager, --set-enabled, crb ]
  - [ dnf, install, -y, epel-release ]

ssh_authorized_keys:
  - ${public_key_openssh}          # Public key from your ansible_key
  - ${lecturer_key}                # Public key from lecturer_key.pub
